- name: Add user docker to run containers
  user:
    name: steve #nom en honor als estibadors. Stevedore en angles
    shell: /bin/bash
    groups: dockerroot
    append: yes
  tags:
    - docker

- name: Resolvconf file
  copy:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  tags:
    - docker

- name: Creates directory /srv/gitlab
  file:
    path: /srv/gitlab
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Sync directory
  synchronize:
    src: gitlab/
    dest: /srv/gitlab
    recursive: yes
    delete: yes
  tags:
    - docker
