- name: Add user docker to run containers
  user:
    name: steve #nom en honor als estibadors. Stevedore en angles
    shell: /bin/bash
    groups: dockerroot
    append: yes
  tags:
    - docker

- name: Resolvconf file
  copy:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  tags:
    - docker

- name: Creates directory "{{ docker_gitlab_dir }}"
  file:
    path: "{{ docker_gitlab_dir }}"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Sync directory
  synchronize:
    src: gitlab/
    dest: "{{ docker_gitlab_dir }}"
    recursive: yes
    delete: no
  tags:
    - docker


- name: Creates directory "{{ docker_gitlab_dir }}/config"
  file:
    path: "{{ docker_gitlab_dir }}/config"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Creates directory "{{ docker_gitlab_dir }}/logs"
  file:
    path: "{{ docker_gitlab_dir }}/logs"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Creates directory "{{ docker_gitlab_dir }}/data"
  file:
    path: "{{ docker_gitlab_dir }}/data"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Start docker service
  docker_service:
    project_name: flask
    definition:
      version: '2'
      services:
        web:
          user: "steve:steve"
          image: gitlab/gitlab-ce:latest
          restart: always
          hostname: 'gitlabjap'
          environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://10.80.87.152'
              sidekiq['concurrency'] = 4
              gitlab_rails['smtp_enable'] = true
              gitlab_rails['smtp_address'] = 'smtp.uib.es'
              gitlab_rails['smtp_port'] = 25
              gitlab_rails['smtp_authentication'] = 'plain'
              gitlab_rails['smtp_enable_starttls_auto'] = true
              gitlab_rails['smtp_domain'] = 'smtp.uib.es'
              gitlab_rails['gitlab_email_from'] = 'gitlabjap@uib.es'
              gitlab_rails['gitlab_email_reply_to'] = 'noreply@uib.es'
          ports:
            - "10080:80"
            - "10022:22"
          volumes:
            - "{{ docker_gitlab_dir }}/config:/etc/gitlab"
            - "{{ docker_gitlab_dir }}/logs:/var/log/gitlab"
            - "{{ docker_gitlab_dir }}/data:/var/opt/gitlab"

  tags:
    - docker

