
- name: Install docker
  yum:
    name: docker
    state: present
  tags: 
    - docker

- name: Install docker-compose
  yum:
    name: docker-compose
    state: present
  tags: 
    - docker


- name: Install python
  yum:
    name: python
    state: present
  tags:
    - docker

- name: Uninstall docker-py to avoid corruption
  yum:
    name: python-docker-py
    state: absent
  tags:
    - docker


- name: Install PyYAML
  yum:
    name: PyYAML
    state: present
  tags:
    - docker

- name: Install Pip
  yum:
    name: python-pip
    state: present
  tags:
    - docker

- name: Install pip docker module
  pip:
    name: docker
  tags:
    - docker

- name: Install pip docker-compose
  pip:
    name: docker-compose
  tags:
    - docker

- name: Add user docker to run containers
  user:
    name: steve #nom en honor als estibadors. Stevedore en angles
    shell: /bin/bash
    groups: dockerroot
    append: yes
  tags:
    - docker

- name: Docker config file
  copy:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  tags:
    - docker

- name: Creates directory "{{ docker_gitlab_dir }}"
  file:
    path: "{{ docker_gitlab_dir }}"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Sync directory
  synchronize:
    src: gitlab/
    dest: "{{ docker_gitlab_dir }}"
    recursive: yes
    delete: no
  tags:
    - docker


- name: Creates directory "{{ docker_gitlab_dir }}/config"
  file:
    path: "{{ docker_gitlab_dir }}/config"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Creates directory "{{ docker_gitlab_dir }}/logs"
  file:
    path: "{{ docker_gitlab_dir }}/logs"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: Creates directory "{{ docker_gitlab_dir }}/data"
  file:
    path: "{{ docker_gitlab_dir }}/data"
    state: directory
    owner: steve
    group: steve
    mode: 0775
  tags:
    - docker

- name: be sure docker is running and enabled
  service: name=docker state=started enabled=yes
  tags: 
    - docker


- name: Start docker service
  become: yes
  become_user: steve
  docker_service:
    project_name: gitlab
    definition:
      version: '2'
      services:
        web:
          image: gitlab/gitlab-ce:latest
          restart: always
          hostname: 'gitlabjap'
          environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://{{ hostname }}'
              sidekiq['concurrency'] = 4
              gitlab_rails['smtp_enable'] = true
              gitlab_rails['smtp_address'] = 'smtp.uib.es'
              gitlab_rails['smtp_port'] = 25
              gitlab_rails['smtp_authentication'] = 'plain'
              gitlab_rails['smtp_enable_starttls_auto'] = true
              gitlab_rails['smtp_domain'] = 'smtp.uib.es'
              gitlab_rails['gitlab_email_from'] = 'gitlabjap@uib.es'
              gitlab_rails['gitlab_email_reply_to'] = 'noreply@uib.es'
          ports:
            - "10080:80"
            - "10022:22"
          volumes:
            - "{{ docker_gitlab_dir }}/config:/etc/gitlab"
            - "{{ docker_gitlab_dir }}/logs:/var/log/gitlab"
            - "{{ docker_gitlab_dir }}/data:/var/opt/gitlab"

  tags:
    - docker

